batch-size: 32
ce-loss-batch-size: 2
ce-loss-n-batches: 2048
evaluation-datasets:
- jailbreakbench
- harmbench_test
filter-train: true
filter-val: true
generation-batch-size: 24
jailbreak-eval-methodologies:
- substring_matching
- llamaguard2
max-new-tokens: 512
model-alias: Llama-2-13b-chat-hf
model-path: meta-llama/Llama-2-13b-chat-hf
n-test: 100
n-train: 128
n-val: 32
refusal-eval-methodologies:
- substring_matching
save-dir: runs